### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by LiuShuaiyr** [microsoft/RepPoints#14]
when I run,python ./mmdetection/tools/train.py ./configs/reppoints_moment_x101_dcn_fpn_2x_mt.py --gpus 0 
TypeError: __init__() got an unexpected keyword argument 'multiscale_mode'

**Comment by muditchaudhary** [comment]
Hi,
Can you post the full error?

**Comment by LiuShuaiyr** [comment]
2019-11-03 20:12:26,557 - INFO - Distributed training: False
2019-11-03 20:12:27,797 - INFO - load model from: open-mmlab://resnext101_32x4d
2019-11-03 20:12:27,984 - WARNING - The model and loaded state dict do not match exactly

missing keys in source state_dict: layer3.19.conv2_offset.bias, layer3.9.conv2_offset.weight, layer3.18.conv2_offset.weight, layer3.21.conv2_offset.bias, layer3.21.conv2_offset.weight, layer3.11.conv2_offset.weight, layer2.1.conv2_offset.bias, layer3.12.conv2_offset.bias, layer3.5.conv2_offset.weight, layer4.2.conv2_offset.weight, layer3.7.conv2_offset.bias, layer3.20.conv2_offset.weight, layer4.0.conv2_offset.bias, layer3.0.conv2_offset.weight, layer3.19.conv2_offset.weight, layer3.2.conv2_offset.bias, layer3.1.conv2_offset.weight, layer3.8.conv2_offset.bias, layer3.17.conv2_offset.weight, layer3.15.conv2_offset.bias, layer3.9.conv2_offset.bias, layer2.2.conv2_offset.weight, layer3.12.conv2_offset.weight, layer3.18.conv2_offset.bias, layer3.6.conv2_offset.weight, layer4.2.conv2_offset.bias, layer2.3.conv2_offset.bias, layer3.13.conv2_offset.bias, layer3.11.conv2_offset.bias, layer2.0.conv2_offset.weight, layer3.10.conv2_offset.weight, layer3.8.conv2_offset.weight, layer3.10.conv2_offset.bias, layer3.3.conv2_offset.bias, layer3.22.conv2_offset.bias, layer3.4.conv2_offset.bias, layer3.5.conv2_offset.bias, layer3.6.conv2_offset.bias, layer3.7.conv2_offset.weight, layer3.13.conv2_offset.weight, layer4.1.conv2_offset.weight, layer3.0.conv2_offset.bias, layer3.2.conv2_offset.weight, layer2.3.conv2_offset.weight, layer3.3.conv2_offset.weight, layer4.1.conv2_offset.bias, layer3.22.conv2_offset.weight, layer3.14.conv2_offset.bias, layer3.16.conv2_offset.bias, layer2.0.conv2_offset.bias, layer2.1.conv2_offset.weight, layer3.1.conv2_offset.bias, layer3.16.conv2_offset.weight, layer3.14.conv2_offset.weight, layer3.4.conv2_offset.weight, layer3.15.conv2_offset.weight, layer3.17.conv2_offset.bias, layer3.20.conv2_offset.bias, layer4.0.conv2_offset.weight, layer2.2.conv2_offset.bias

Traceback (most recent call last):
  File "./mmdetection/tools/train.py", line 108, in <module>
    main()
  File "./mmdetection/tools/train.py", line 86, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/ls/code/Object_detection/RepPoints/mmdetection/mmdet/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ls/code/Object_detection/RepPoints/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'multiscale_mode'

**Comment by LiuShuaiyr** [comment]
> Hi,
> Can you post the full error?

2019-11-03 20:12:26,557 - INFO - Distributed training: False
2019-11-03 20:12:27,797 - INFO - load model from: open-mmlab://resnext101_32x4d
2019-11-03 20:12:27,984 - WARNING - The model and loaded state dict do not match exactly

missing keys in source state_dict: layer3.19.conv2_offset.bias, layer3.9.conv2_offset.weight, layer3.18.conv2_offset.weight, layer3.21.conv2_offset.bias, layer3.21.conv2_offset.weight, layer3.11.conv2_offset.weight, layer2.1.conv2_offset.bias, layer3.12.conv2_offset.bias, layer3.5.conv2_offset.weight, layer4.2.conv2_offset.weight, layer3.7.conv2_offset.bias, layer3.20.conv2_offset.weight, layer4.0.conv2_offset.bias, layer3.0.conv2_offset.weight, layer3.19.conv2_offset.weight, layer3.2.conv2_offset.bias, layer3.1.conv2_offset.weight, layer3.8.conv2_offset.bias, layer3.17.conv2_offset.weight, layer3.15.conv2_offset.bias, layer3.9.conv2_offset.bias, layer2.2.conv2_offset.weight, layer3.12.conv2_offset.weight, layer3.18.conv2_offset.bias, layer3.6.conv2_offset.weight, layer4.2.conv2_offset.bias, layer2.3.conv2_offset.bias, layer3.13.conv2_offset.bias, layer3.11.conv2_offset.bias, layer2.0.conv2_offset.weight, layer3.10.conv2_offset.weight, layer3.8.conv2_offset.weight, layer3.10.conv2_offset.bias, layer3.3.conv2_offset.bias, layer3.22.conv2_offset.bias, layer3.4.conv2_offset.bias, layer3.5.conv2_offset.bias, layer3.6.conv2_offset.bias, layer3.7.conv2_offset.weight, layer3.13.conv2_offset.weight, layer4.1.conv2_offset.weight, layer3.0.conv2_offset.bias, layer3.2.conv2_offset.weight, layer2.3.conv2_offset.weight, layer3.3.conv2_offset.weight, layer4.1.conv2_offset.bias, layer3.22.conv2_offset.weight, layer3.14.conv2_offset.bias, layer3.16.conv2_offset.bias, layer2.0.conv2_offset.bias, layer2.1.conv2_offset.weight, layer3.1.conv2_offset.bias, layer3.16.conv2_offset.weight, layer3.14.conv2_offset.weight, layer3.4.conv2_offset.weight, layer3.15.conv2_offset.weight, layer3.17.conv2_offset.bias, layer3.20.conv2_offset.bias, layer4.0.conv2_offset.weight, layer2.2.conv2_offset.bias

Traceback (most recent call last):
  File "./mmdetection/tools/train.py", line 108, in <module>
    main()
  File "./mmdetection/tools/train.py", line 86, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/ls/code/Object_detection/RepPoints/mmdetection/mmdet/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ls/code/Object_detection/RepPoints/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'multiscale_mode'

**Comment by muditchaudhary** [comment]
Seems like you are using the updated version of mmdetection. RepPoints doesn't work with the latest version of mmdetection. I'd recommend you to clone the mmdetection folder from the RepPoints repository and then build mmdetection again using:
```
cd mmdetection
pip install -v -e .
```
In order to avoid the automatic update of the mmdetection, delete the git files from the mmdetection folder. Let me know if you further receive any errors.
